apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xmpro.fullname" . }}-sh
  labels:
    app: {{ include "xmpro.fullname" . }}-sh
    {{- include "xmpro.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.sh.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "xmpro.fullname" . }}-sh
      {{- include "xmpro.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.sh.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "xmpro.fullname" . }}-sh
        {{- include "xmpro.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "xmpro.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: sh
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.sh.image.repository }}:{{ .Values.sh.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.sh.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.sh.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}