apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    https://ai.{{ .Values.caddy.dns_zone_name }} {
      reverse_proxy /* xmpro-ai:5000
    }
    https://ad.{{ .Values.caddy.dns_zone_name }} {
      reverse_proxy /* xmpro-ad:5000
    }
    https://ds.{{ .Values.caddy.dns_zone_name }} {
      reverse_proxy /* xmpro-ds:5000
    }
