apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: 1Gi